### ISSUE TITLE
Ausencia de extensão de arquivo

### ISSUE THREAD

**Issue by PLeonLopes** [M1zeria/Estudo-Fun-es#1]
falta da extensão `.py` nos arquivos [Lista 5-1](https://github.com/M1zeria/Estudo-Fun-es/blob/main/Lista%205-1) e [Lista 5-2](https://github.com/M1zeria/Estudo-Fun-es/blob/main/Lista%205-2)

**Comment by M1zeria** [comment]
obgd amigo :D
